[package]
name = "media-player"
version = "0.1.0"
description = "Cross-platform local media player"
authors = ["moritzbrantner"]
edition = "2021"

[lib]
name = "media_player_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
